services:
  flask_backend:
    build: .
    environment:
      VITE_FLASK_PORT: 5174
      NGINX_PORT: 5173
    ports:
      - "8000:5000"
  vite_frontend:
    build: frontend
    environment:
      VITE_FLASK_PORT: 5174
      NGINX_PORT: 5173