services:
  flask_backend:
    build: .
    environment:
      FLASK_PORT: 5174
      NGINX_PORT: 5173
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5174:5174"
  vite_frontend:
    build: ./frontend
    environment:
      VITE_FLASK_PORT: 5174
      NGINX_PORT: 5173
    ports:
      - "5173:5173"