services:
  flask_backend:
    build: .
    environment:
      FLASK_PORT: 5174
      NGINX_PORT: 5173
      JWT_SECRET: ${JWT_SECRET}
  vite_frontend:
    build: ./frontend
    environment:
      VITE_FLASK_PORT: 5174
      NGINX_PORT: 5173
    ports:
      - "127.0.0.1:8080:8080"